local identifiers = require("H3MP.Core.messageidentifiers")

local ID_MAX = 2048

local contents = [[
/*
This file was generated by generate-message-identifiers.lua
Please do not directly modify this cs file!
To regenerate, go to root dir of this project and run
"lua scripts/generate-message-identifiers.lua H3MP/Core/MessageIdentifiers.cs"
*/

namespace H3MP.Core;

public static class MessageIdentifier
{
    public const ushort ID_MAX = %d;
%s
}
]]

---@param opts { name: string, ntype: string?, members: { name: string, value: integer }[], accessibility: string? }
local function enum(opts)
    opts.ntype = opts.ntype or "ushort"
    opts.accessibility = opts.accessibility or "public"

    local str = [[

    %s enum %s : %s
    {
%s
    }
]]
    local vals = ""
    for i, val in ipairs(opts.members) do
        vals = vals .. string.format("        %s = %d,\n", val.name, val.value)
    end

    return string.format(str, opts.accessibility, opts.name, opts.ntype, vals)
end

local enums = ""

local count = 1
for _, value in ipairs(identifiers) do
    ---@type { name: string, value: integer }[]
    local vals = {}
    for _, v in ipairs(value.values) do
        vals[#vals + 1] = { name = v, value = count }
        count = count + 1
    end

    enums = enums .. enum {
        name = value.name,
        members = vals
    }
end

if count < ID_MAX then
    local vals = {}
    for i = count, ID_MAX do
        vals[#vals + 1] = { name = "RESERVED_" .. i, value = i }
    end

    enums = enums .. enum {
        name = "Reserved",
        members = vals
    }
end

local f = io.open(arg[1] or "MessageIdentifiers.cs", "w")
if f == nil then return error "Could not open file for reading!" end
f:write(string.format(contents, ID_MAX, enums))
f:close()
